name: 'publish'

on:
  push:
    branches:
      - 'main'
    paths:
      - 'articles/**'
jobs:
  publish:
    name: publish new article
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: blogpub
        uses: protiumx/blogpub@v0.4.1
        with:
          articles_folder: articles
          devto_api_key: ${{ secrets.DEVTO_API_KEY }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
        
